### ISSUE TITLE
'export' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Vandivier** [apifytech/actor-quick-start#1]
Issue title is the error I'm getting on `npm run test-local`. Although CLI still prints "Input message: Hello world!" I also still get OUTPUT. So maybe it is innocuous.

I am using Git Bash on Windows. I believe export isn't valid on Windows. You can use the `cross-env` package I believe to get the desired functionality in a platform agnostic way.

**Comment by jancurn** [comment]
You're right, I've just added the `cross-env` package. Many thanks for the feedback!
